export const QUOTE_SERVICE_CURRENCY_PAIR_PRICE_REPOSITORY = Symbol('QUOTE_SERVICE_CURRENCY_PAIR_PRICE_REPOSITORY')
export const QUOTE_SERVICE_COMMISSION_REPOSITORY = Symbol('QUOTE_SERVICE_COMMISSION_REPOSITORY')
export const QUOTE_SERVICE_QUOTE_SERVICE = Symbol('QUOTE_SERVICE_QUOTE_SERVICE')
